online_learning_platform/main_app/urls.py
from main_app import views
from django.urls import path
from django.contrib import admin

app_name='main_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('categories/', views.categories, name='categories'),
    path('category/<str:title>/courses/', views.courses_in_category, name='courses_in_category'),
    path('courses/', views.course_list, name='course_list'),
    path('course/<int:course_id>/', views.course_page, name='course_page'),
    path('teacher/<int:id>/', views.teacher_page, name='teacher_page'),
    path('quiz/<slug:course_title>/', views.quiz_view, name='quiz_view'),
    path('assignment/<int:course_id>/', views.assignment_view, name='assignment_view'),
    path('profile/', views.profile, name='profile'),
    path('course/<int:course_id>/enroll/', views.add_course_to_user, name='add_course_to_user'),
] 

online_learning_platform/online_learning_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('main_app/', include('main_app.urls')),
    path('logout', views.user_logout, name='logout'),
    path('categories/', views.categories, name='categories'),
    path('category/<str:title>/courses/',
         views.courses_in_category, name='courses_in_category'),
    path('teacher/<int:id>/', views.teacher_page, name='teacher_page'),
    path('profile/', views.profile, name='profile'),
    path('assignment/<int:course_id>/',
         views.assignment_view, name='assignment_view'),
    path('course/<int:course_id>/enroll/',
         views.add_course_to_user, name='add_course_to_user'),
    path('course/<int:course_id>/', views.course_page, name='course_page'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

online_learning_platform/main_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

class Images(models.Model):
    profile_pic = models.ImageField(upload_to='profile_pics/',blank=True)
    
    def __str__(self):
        return self.profile_pic.name if self.profile_pic else 'No image'


class Category(models.Model):
    title = models.CharField(max_length=200)
    description=models.TextField(blank=True)

    def __str__(self):
        return self.title
    


class Teacher(models.Model):
    id=models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(null=True, blank=True)
    email=models.CharField(max_length=100, blank=True)
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Course(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    video_link = models.URLField(max_length=200, blank=True, null=True)
    release_date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Quiz(models.Model):
    title = models.CharField(max_length=200)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct_option = models.CharField(max_length=200)


class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'course')

    def __str__(self):
        return f"{self.user.username} - {self.course.title}"

class Assignment(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank= True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    deadline= models.DateField(blank=True)

    def __str__(self):
        return self.title

online_learning_platform/main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from main_app.models import UserProfileInfo, Category, Course, Teacher, Images, Assignment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model= User
        fields = ('username', 'email', 'password',)

class TeacherForm(forms.ModelForm):
    class Meta():
        model=Teacher
        fields = ('id', 'first_name', 'last_name','bio','email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)


class CategoryForm(forms.ModelForm):
    class Meta():
        model= Category
        fields = ('title','description',)

class CourseForm(forms.ModelForm):
    class Meta():
        model= Course
        fields = ('id','title','teacher', 'video_link', 'description','release_date','teacher',)


class ImagesForm(forms.ModelForm):
    class Meta():
        model=Images
        fields=('profile_pic',)

class AssignmentForm(forms.ModelForm):
    class Meta():
        model=Assignment
        fields=('title','description','deadline',)

online_learning_platform/main_app/views.py
from django.shortcuts import render,redirect, get_object_or_404
from main_app.forms import UserForm, UserProfileInfoForm, TeacherForm, AssignmentForm
from .models import UserProfileInfo, UserCourse, Course, Assignment, Category, Teacher, Question, Quiz
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from urllib.parse import unquote
from django.utils.text import slugify
from django.core.files.storage import FileSystemStorage


def index(request):
    return render(request, 'main_app/index.html')


@login_required
def profile(request):
    enrolled_courses = UserCourse.objects.filter(user=request.user)
    return render(request, 'main_app/profile.html', {'user': request.user, 'enrolled_courses': enrolled_courses})

@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def categories(request):
    categories=Category.objects.all()
    return render(request, 'main_app/categories.html', {'categories': categories})

def course_list(request):
    course_list = Course.objects.all()
    return render(request, 'main_app/course_list.html', {'courses': course_list})


def teacher_page(request,id):
    teacher = get_object_or_404(Teacher, id=id)
    courses_same_teacher = Course.objects.filter(teacher=teacher)
    return render(request, 'main_app/teacher_page.html', {'teacher': teacher, 'courses_same_teacher': courses_same_teacher})


# def course_page(request, course_id):
#     course = Course.objects.get(id=course_id)
#     return render(request, 'main_app/course_page.html', {'course': course})

@login_required
def add_course_to_user(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    UserCourse.objects.get_or_create(user=request.user, course=course)
    return redirect('course_page', course_id=course.id)

def convert_to_embed_url(url):
    if "watch?v=" in url:
        return url.replace("watch?v=", "embed/")
    elif "youtu.be/" in url:
        return url.replace("youtu.be/", "youtube.com/embed/")
    return url

def course_page(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    user_enrolled = UserCourse.objects.filter(user=request.user, course=course).exists()
    url_safe_title = slugify(course.title)
    quiz_exists = Quiz.objects.filter(course=course).exists()
    assignment_exists = Assignment.objects.filter(course=course).exists()
    if course.video_link:
        course.video_link = convert_to_embed_url(course.video_link)
    return render(request, 'main_app/course_page.html', {
        'course': course,
        'user_enrolled': user_enrolled,
        'quiz_exists': quiz_exists,
        'assignment_exists': assignment_exists,
        'url_safe_title': url_safe_title,
    })

def courses_in_category(request, title):
    category = Category.objects.get(title=title)
    courses_in_category = Course.objects.filter(category=category)
    return render(request, 'main_app/courses_in_category.html', {'courses_in_category': courses_in_category, 'category': category})

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form =UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
        
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic =request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
        return render(request, 'main_app/login.html')

    else:
        user_form =UserForm()
        profile_form = UserProfileInfoForm
    return render(request, 'main_app/registration.html',
                {'user_form':user_form,
                 'profile_form':profile_form,
                 'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('categories'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'main_app/login.html', {})
    


def quiz_view(request, course_title):
    decoded_course_title = course_title.replace('-', ' ').lower()
    course = get_object_or_404(Course, title__iexact=decoded_course_title)
    
    quiz = get_object_or_404(Quiz, course=course)
    questions = Question.objects.filter(quiz=quiz)
    results = None

    if request.method == 'POST':
        results = []
        for question in questions:
            selected_option = request.POST.get(f'question_{question.id}')
            is_correct = (selected_option == question.correct_option)
            results.append({
                'question': question,
                'selected_option': selected_option,
                'is_correct': is_correct,
                'correct_option': question.correct_option
            })

    return render(request, 'main_app/quiz.html', {
        'quiz': quiz,
        'questions': questions,
        'results': results,
    })

def assignment_view(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    assignments = Assignment.objects.filter(course=course)
    return render(request, 'main_app/assignment.html', {'course': course, 'assignments': assignments})

online_learning_platform/main_app/templates/main_app/assignment.html
{% extends "main_app/base.html" %}

{% block body_block %}

<h1>Assignments for {{ course.title }}</h1>
   
    <ul>
        {% for assignment in assignments %}
            <li>
                <h3>{{ assignment.title }}</h3>
                <p><h4>Guidelines:</h4> {{ assignment.description }}</p>
                <p><h4>Deadline:</h4> {{ assignment.deadline }}</p>
                <div class="item">
                    <p><em>For any questions contact <a href="{% url 'main_app:teacher_page' course.teacher.id %}">{{ course.teacher }}</a></em></p>
                </div>
                
            </li>
        {% empty %}
            <li>No assignments available for this course.</li>
        {% endfor %}
        <p><h4>Answer the assignment now:</h4></p>
        <label for="file">Upload PDF File:</label><br>
        <input type="file" id="file" name="file"><br><br>
        
        <button type="submit">Submit</button>
    </ul>
    <div class="item">
        <a href="{% url 'main_app:course_page' course.id %}">Back to the course page</a>
    </div>
    
    
    <style>
        body {
             background-color: rgba(201, 191, 191, 0.801)
            }
        
        .item a {
          text-decoration: none;
          color: #497a0876;
          font-weight: bold;
      }
      
        .item a:hover {
          text-decoration: underline;
      }
    </style>
      
{% endblock %}

online_learning_platform/main_app/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'images/styling.css' %}" />
    <style></style>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'images/logo.png' %}" alt="Logo" />
          <span>G3 Online Learning Platform!!!!!</span>
        </a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">My profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'categories' %}">Categories</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %} {% endblock %}
    </div>

    <div class="footer">
      &copy; 2024 G3 Online Learning Platform. All rights reserved.
    </div>
  </body>
</html>

online_learning_platform/main_app/templates/main_app/categories.html
{% extends "main_app/base.html" %}

{% block body_block %}

<style>
.container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 20px;
}

.item {
    border: 1px solid #ccc;
    padding: 20px;
    margin: 10px;
    width: 300px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s, box-shadow 0.3s;
    background-color: #fff;
}

.item:hover {
    transform: translateY(-10px);
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
}

.item h3 {
    color: #0a502792;
    margin-bottom: 10px;
}

.item p {
    color: #333;
    margin-bottom: 15px;
}

.item a {
    text-decoration: none;
    color: #497a0876;
    font-weight: bold;
}

.item a:hover {
    text-decoration: underline;
}


body {
    background-color: rgba(201, 191, 191, 0.801)
    }
</style>

<div class="container">
    {% for category in categories %}
    <div class="item">
        <h3>{{ category.title }}</h3>
        <p><strong>Description: </strong> {{ category.description }}</p>
        <a href="{% url 'courses_in_category' category.title %}">View courses in this category</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

online_learning_platform/main_app/templates/main_app/course_list.html
{% extends "main_app/base.html" %}

{% block body_block %}

{% for course in courses %}
    <div class="item">
        <h3>{{ course.title }}</h3>
    </div>
    {% endfor %}
    <style>
        body {
             background-color: rgba(201, 191, 191, 0.801)
            }
        
        .item a {
          text-decoration: none;
          color: #497a0876;
          font-weight: bold;
      }
      
        .item a:hover {
          text-decoration: underline;
      }
      </style>
{% endblock %}

online_learning_platform/main_app/templates/main_app/course_page.html
{% extends "main_app/base.html" %} {% block body_block %}
<h2>{{ course.title }}</h2>
<p>{{ course.description }}</p>

<div class="item">
  <p>Teacher: <a href="{% url 'main_app:teacher_page' course.teacher.id %}">{{ course.teacher }} </a></p>
</div>

<p>Release Date: {{ course.release_date }}</p>

<h2>Material</h2>

<h3>Videos:</h3>
{% if course.video_link %}        
  {% with course.video_link|cut:"watch?v=" as embed_link %}       
    <iframe width="560" height="315" src="{{ course.video_link }}" frameborder="0" allowfullscreen></iframe>
  {% endwith %}
{% endif %}
<br>
{% if quiz_exists %}
<h3>Quizes:</h3>
<form method="get" action="{% url 'main_app:quiz_view' url_safe_title %}">
  <button type="submit">{{ course.title }} Quiz</button>
</form>
{% else %}
<p>No quiz available for this course.</p>
{% endif %} 
<br>

{% if assignment_exists %}
    <h3>Assignment:</h3>
    <form method="get" action="{% url 'main_app:assignment_view' course.id %}">
      <button type="submit">{{ course.title }} Assignment</button>
    </form>

{% else %}
    <p>No assignment available for this course.</p>
{% endif %}

<br>

<h3>Enrollment:</h3>
{% if not user_enrolled %}
  <form method="post" action="{% url 'add_course_to_user' course.id %}">
    {% csrf_token %}
    <button type="submit">Enroll in this Course</button>
  </form>
{% else %}
  <p>You are already enrolled in this course.</p>
{% endif %}
<div class="item">
  <p><a href="{% url 'categories' %}">Back to the categories</a></p>
</div>


<style>
  body {
       background-color: rgba(201, 191, 191, 0.801)
      }
  
  .item a {
    text-decoration: none;
    color: #497a0876;
    font-weight: bold;
}

  .item a:hover {
    text-decoration: underline;
}
</style>


{% endblock %}

online_learning_platform/main_app/templates/main_app/courses_in_category.html
{% extends "main_app/base.html" %}

{% block body_block %}
    {% if category %}
        <h2>Courses in {{ category.title }}</h2>
        {% if courses_in_category %}
            {% for course in courses_in_category %}
                <div class="item">
                    <a href="{% url 'main_app:course_page' course.id %}">{{ course.title }} </a></li>
                    <p>{{ course.description }}</p>
                
                </div>
            {% endfor %}
        {% else %}
            <p>No courses found in this category.</p>
        {% endif %}
    {% else %}
        <p>Category not found.</p>
    {% endif %}
    <style>
        body {
             background-color: rgba(201, 191, 191, 0.801)
            }
        
        .item a {
          text-decoration: none;
          color: #497a0876;
          font-weight: bold;
      }
      
        .item a:hover {
          text-decoration: underline;
      }
      </style>
{% endblock %}

online_learning_platform/main_app/templates/main_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Home</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" />
  {% load static %}
  <link rel="stylesheet" href="{% static 'images/styling_index.css' %}" />
  <style>
    body {
      background-image: url('{% static "images/background.jpg" %}');
    }
   
  </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container">
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" alt="Logo" />
            <span>G3 Online Learning Platform!!!!!</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">My profile</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'categories' %}">Categories</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
     
      <div class="container">
        <br><br><br><br><br><br><br><br>
        <div class="row justify-content-center">
            <div class="col-md-4 offset-md-4 custom-border text-center">
                <h3 class="header" align="center">Welcome to G3 Online Course Platform!</h3>
                <ul class="nav flex-column">
                    {% if not user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link btn" href="{% url 'main_app:register' %}">New here? Register now</a></li>
                    <br>
                    <li class="nav-item"><a class="nav-link btn" href="{% url 'main_app:user_login' %}">Already have an account? Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

  <div class="footer">
    &copy; 2024 G3 Online Learning Platform. All rights reserved.
  </div>
</body>
</html>

online_learning_platform/main_app/templates/main_app/login.html
{% extends "main_app/base.html" %}

{% block body_block %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Please Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'main_app:user_login' %}" method="post">
                        {% csrf_token %}  
                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="Enter Username">
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password">
                        </div>
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <small>&copy; 2024 G3 Online Learning Platform. All rights reserved.</small>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

online_learning_platform/main_app/templates/main_app/profile.html
{% extends "main_app/base.html" %}

{% block body_block %}
<br><br><br>
<div class="container-profile">
    <h1>Welcome {{ user.username }}</h1>
    <h2>Enrolled Courses</h2>
    <ul>
        {% for user_course in enrolled_courses %}
            <li>
                <a href="{% url 'course_page' user_course.course.id %}">{{ user_course.course.title }}</a>
            </li>
        {% endfor %}
    </ul>
    <div class="item">
        <p><a href="{% url 'categories' %}">See all the courses</a></p>
    </div>
    
</div>

<style>
        body {
             background-color: rgba(201, 191, 191, 0.801)
            }
        
        .item a {
          text-decoration: none;
          color: #497a0876;
          font-weight: bold;
      }
      
        .item a:hover {
          text-decoration: underline;
      }
    
    .container-profile  {
        margin-top: 0px;
        background: #c6c9cca1;
        padding: 25px;
        border-radius: 30px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .container-profile h1 {
        font-size: 3.8rem;
        color: #133a2b;
        margin-bottom: 35px;
        text-align: center;
        font-weight: bold;
    }

    .container-profile h2 {
        font-size: 2rem;
        color: #6c757d;
        margin-bottom: 30px;
        text-align: center;
    }

    .container-profile ul {
        list-style-type: none;
        padding: 0;
    }

    .container-profile ul li {
        background: #cac2c29f;
        margin: 10px 0;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        transition: transform 0.3s, box-shadow 0.3s;
    }

    .container-profile ul li:hover {
        transform: scale(1.02);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .container-profile ul li a {
        display: block;
        padding: 15px;
        color: black;
        text-decoration: none;
        font-size: 2.0rem;
        border-radius: 5px;
        transition: color 0.3s;
    }

    .container-profile ul li a:hover {
        color: #00b30f37;
    }

    .container-profile p a {
        color: #21644a91;
        text-decoration: none;
        font-size: 1.35rem;
        font-weight: bold;
        transition: color 0.3s;
    }

    .container-profile p a:hover {
        color: #0c331491;
    }
</style>

{% endblock %}

online_learning_platform/main_app/templates/main_app/registration.html
{% extends "main_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card rounded-3 shadow">
                <div class="card-header bg-light border-bottom-0 text-center">
                    {% if registered %}
                    <h2 class="text-black mb-0">Thank You for Registering!</h2>
                    {% else %}
                    <h2 class="text-black mb-0">Register Here!</h2>
                    <p class="text-muted">Fill out the form below</p>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% if not registered %}
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {{ user_form.as_p }}
                        {{ profile_form.as_p }}
                        <div class="mt-4 text-center">
                            <button type="submit" class="btn btn-dark btn-lg">Register</button>
                        </div>
                    </form>
                    {% endif %}
                </div>
                {% if registered %}
                <div class="card-footer bg-light border-top-0 text-center">
                    <a href="{% url 'main_app:login' %}" class="btn btn-outline-dark btn-lg">Go to Login</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

online_learning_platform/main_app/templates/main_app/teacher_page.html
{% extends "main_app/base.html" %}

{% block body_block %}
    <h3>{{ teacher.first_name }} {{ teacher.last_name }}</h3>
    <p>{{ teacher.bio }}</p>
    <p><h5>Email adress:</h5>
    <div class="item">
       <a href= >{{ teacher.email }} </a></p> 
    </div>
    <h4>Other courses of {{ teacher.first_name }}:</h4>
    {% if courses_same_teacher %}
        <ul>
        {% for course in courses_same_teacher %}
            <li>
                <div class="item">
                    <a href="{% url 'main_app:course_page' course.id %}">{{ course.title }}</a>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No other courses available.</p>
    {% endif %}
    <style>
        body {
             background-color: rgba(201, 191, 191, 0.801)
            }
        
        .item a {
          text-decoration: none;
          color: #497a0876;
          font-weight: bold;
      }
      
        .item a:hover {
          text-decoration: underline;
      }
      </style>
{% endblock %}